stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-adoptopenjdk-11
          shellScript: mvn package -DskipTests
  - name: Build Docker with DIND
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: docker.dev.folio.org/mod-template-engine:vega-latest
          pushRemote: true
          registry: docker.dev.folio.org
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-wntj9:vega-helmcharts-mod-template-engine
          version: 15.9.0
          answers:
            image.repository: docker.dev.folio.org/mod-template-engine
            image.tag: vega-latest
          targetNamespace: vega
          name: mod-template-engine
timeout: 60
notification: {}
